#!/usr/bin/env dash
exec ~/.config/bspwm/rules &
export QT_QPA_PLATFORMTHEME=qt5ct
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d '1' '2' '3' '4' '5' '6'
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config click_to_focus button1
bspc config focus_follows_pointer false
bspc config gapless_monocle      true

bspc config focused_border_color "#e6b450"
bspc config normal_border_color "#4d5566"
bspc config active_border_color "#ffb454"
bspc config presel_feedback_color "#d4bfff"
exec $HOME/.startup &
