#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -no-config -location 8 -yoffset 250 -xoffset 600 -theme ~/.config/rofi/themes/nordtheme -sep "|" rofi -show drun -dmenu -i -p '襤' -width 12 -hide-scrollbar -line-padding 6 -padding 20 -lines 5 <<< " Lock| Logout| Reboot| Shutdown| Sleep")"
            case "$MENU" in
                *Lock) betterlockscreen -l ;;
                *Logout) bspc quit;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff ;;
		*Sleep) systemctl suspend ;;
            esac
